---

comparisons:
- comparison:
    path: "../alignments/comp01-1species-20genomes-500000chars.nex"
- comparison:
    path: "../alignments/comp02-1species-20genomes-500000chars.nex"
- comparison:
    path: "../alignments/comp03-1species-20genomes-500000chars.nex"

global_comparison_settings:
    ploidy: 2
    genotypes_are_diploid: false
    markers_are_dominant: false
    population_name_delimiter: "-"
    population_name_is_prefix: true
    constant_sites_removed: false
    equal_population_sizes: false
    parameters:
        population_size:
            value: 0.002
            estimate: true
            prior:
                gamma_distribution:
                    shape: 4.0
                    scale: 0.0005
                    offset: 0.0001
        root_relative_population_size:
            value: 0.1
            estimate: true
            prior:
                gamma_distribution:
                    shape: 5.0
                    scale: 0.01
                    offset: 0.05
        freq_1:
            value: 0.5
            estimate: false

        mutation_rate:
            value: 1.0
            estimate: false

    operators:
        TimeSizeRateMixer:
            weight: 0
        TimeSizeRateScaler:
            weight: 0
        EventTimeScaler:
            weight: 0
        RootPopulationSizeScaler:
            weight: 1
            scale: 0.1
        LeafPopulationSizeScaler:
            weight: 1
            scale: 0.1
        MutationRateScaler:
            weight: 0
        FreqMover:
            weight: 0
        TimeRootSizeMixer:
            weight: 0


event_model_prior:
    dirichlet_process:
        parameters:
            concentration:
                value:      1.414216
                estimate:   false

event_time_prior:
    gamma_distribution:
        shape: 4.0
        scale: 0.000475
        offset: 0.0001

mcmc_settings:
    chain_length: 75000
    sample_frequency: 50

operator_settings:
    auto_optimize: true
    auto_optimize_delay: 1000
    operators:
        ModelOperator:
            weight: 10
            number_of_auxiliary_categories: 4
        ConcentrationScaler:
            weight: 0
        TimeSizeRateMixer:
            weight: 6
            scale: 0.1
        TimeSizeRateScaler:
            weight: 4
            scale: 0.1
        EventTimeScaler:
            weight: 1
            scale: 0.1
        TimeRootSizeMixer:
            weight: 6
            scale: 0.05
